### ISSUE TITLE
(create_division) DetachedInstanceError:  Parent instance is not bound to a Session; lazy load operation of attribute 'parameter' cannot proceed

### ISSUE THREAD

**Issue by Ploppz** [mariiuus/PIG#58]
Creating a division. The form data is included in the output:

```
5:52:44 PM web.1 |  Registering division...
5:52:44 PM web.1 |  Input: ImmutableMultiDict([('Division', 'trsa'), ('Parameter1', 'srtra'), ('Type1', 'Enum'), ('Min1', ''), ('Max1', ''), ('Option1_1', 'test456'), ('Option1_2', 'test64565')])
5:52:44 PM web.1 |  [2017-03-16 17:52:44,095] ERROR in app: Exception on /create_division [POST]
5:52:44 PM web.1 |  Traceback (most recent call last):
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
5:52:44 PM web.1 |      response = self.full_dispatch_request()
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
5:52:44 PM web.1 |      rv = self.handle_user_exception(e)
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
5:52:44 PM web.1 |      reraise(exc_type, exc_value, tb)
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
5:52:44 PM web.1 |      raise value
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
5:52:44 PM web.1 |      rv = self.dispatch_request()
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
5:52:44 PM web.1 |      return self.view_functions[rule.endpoint](**req.view_args)
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
5:52:44 PM web.1 |      return func(*args, **kwargs)
5:52:44 PM web.1 |    File "/home/ploppz/ntnu/2017_A/tdt4140_prgutvikl/PIG/pig/views.py", line 82, in create_division
5:52:44 PM web.1 |      division_creator.register_division(current_user, request.form)
5:52:44 PM web.1 |    File "/home/ploppz/ntnu/2017_A/tdt4140_prgutvikl/PIG/pig/scripts/create_division.py", line 99, in register_division
5:52:44 PM web.1 |      spec.parameter = param
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
5:52:44 PM web.1 |      instance_dict(instance), value, None)
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 797, in set
5:52:44 PM web.1 |      LOAD_AGAINST_COMMITTED)
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
5:52:44 PM web.1 |      value = self.callable_(state, passive)
5:52:44 PM web.1 |    File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state
5:52:44 PM web.1 |      (orm_util.state_str(state), self.key)
5:52:44 PM web.1 |  sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <NumberParam at 0x7f746c972f28> is not bound to a Session; lazy load operation of attribute 'parameter' cannot proceed

```

**Comment by Ploppz** [comment]
Maybe related, from irc `#sqlalchemy` upon sharing the model classes for Parameter and EnumVariant:

> may i ask why you are using lazy=dynamic everywhere?
> because it's almost never a good idea
> values = db.relationship('Value', secondary=parameter_value,
> backref=db.backref('parameter',lazy='dynamic')) -- especially not on that
> side of a many-to-one relationship
> parameter will always return only one row, so lazy=True makes so much more
> sense there

**Comment by Ploppz** [comment]
Apparently, this means that the NumberParam instance isn't connected to a session, so `.parameter` can't be accessed on it. "It would have to be loaded from the DB, and it needs a session to do it." (irc)
> http://docs.sqlalchemy.org/en/rel_1_1/orm/session_state_management.html#quickie-intro-to-object-states
